### ISSUE TITLE
I can't click the download button

### ISSUE THREAD

**Issue by Dravengard** [Official-Husko/bug-reports#2]
**Information**  
Product: (Multporn-Image-Downloader-v2)  
Version: (3.0p)  

**Is your feature request related to a problem? Please describe.**
I cannot click the download button because my screen may be too "short" (1366 x 768). It's just a little off screen right below the progression bar and there's nothing I can do about it.

![image](https://user-images.githubusercontent.com/73265673/96817094-83eb3d00-1416-11eb-810d-131ef81c82ac.png)

**Describe the solution you'd like**
If you could please relocate the download button to the side of the rest of the download options or maybe you could allow me to resize the window (as it is currently impossible to do so), it would be greatly appreciated

**Additional context**
I really want to be able to use this tool. It seems really good and well made

**Comment by Official-Husko** [comment]
Greetings, i'm sorry for the inconvenience. I made a quick fix and it its available here: [Download](https://github.com/Official-Husko/multporn-image-downloader-v2/releases/tag/v3.0.1p)

If this fixed your issue then please close the Issue.

**Comment by Dravengard** [comment]
Thank you so much. This fixes my problem
