### ISSUE TITLE
RAR file download is corrupt

### ISSUE THREAD

**Issue by billybob884** [Official-Husko/bug-reports#4]
**Information**  
Product: Multporn-Image-Downloader-v2  
Version: v2  
OS: e.g Windows  
  
**Describe the bug**  
Trying to download the RAR archive from your "How to use" section, but the file is corrupt. Tried on two machines so I'm pretty sure your uploaded file is no good?

**Comment by Official-Husko** [comment]
I will check it out rn, it shouldn't be corrupt tho because many users already downloaded it and they had no issue with. Are you using IDM by any chance to download the software?

**Comment by Official-Husko** [comment]
I will close this issue in 4 days unless you provide more information or an update from your side. Feel free to close the issue yourself if has been solved.

**Comment by billybob884** [comment]
Yea the download still gives a corrupt archive, very strange.

Downloaded from this location:
https://github.com/Official-Husko/multporn-image-downloader-v2/releases/tag/v3.0p

Error:
https://i.imgur.com/T1ED1ki.png

**Comment by oguh43** [comment]
I can even extract it on my phone... Quite strange

**Comment by Official-Husko** [comment]
Okay on my device i do not experience that issue. I tried the specific version again which is v3.0p. I will make a special reupload for you and other users who might get that error in the future.

**Comment by Official-Husko** [comment]
I will close this issue, if you experience the same problem still then reopen it and give more details on things you tried.
